package Arch;

public enum EventType {
    ALARM_ADDED,
    ALARM_ADD_REQUEST,
    ALARM_SYNC,
    ALARM_WENT_OFF,
    SERVICE_MESSAGE,
    CLOCK_UPDATED,
    CLOCK_SYNC,
    CLOCK_TOGGLE,
    CLOCK_UPDATE_REQUEST,
    CLIENT_CONNECT_REQUEST
}
