package Arch;

public enum EventType {
    ALARM_ADDED,
    ADD_ALARM_REQUEST,
    ALARM_WENT_OFF,
    SERVICE_MESSAGE,
    CLOCK_UPDATED,
    CLOCK_SYNC,
    CLOCK_TOGGLE,
    CLOCK_UPDATE_REQUEST,
}
